### ISSUE TITLE
All builds failing

### ISSUE THREAD

**Issue by vDokkaebi** [Petrosz007/RedPandaBot#9]
SonarCloud is complaining about the following issue on GitHub Actions:
`The format of the analysis property sonar.login= is invalid`

**Comment by Petrosz007** [comment]
I'll look into it

**Comment by Petrosz007** [comment]
> Seems like secrets are not yet supported on forks on GitHub. Please make sure that this one is declared on the account that forked the repo as well.
https://community.sonarsource.com/t/sonarcloud-analysis-fails-on-prs-for-c-project-on-github/34260

I'll disable SonarCloud for PR's and only run it on the `main` branch.

**Comment by Petrosz007** [comment]
Rebase your branches on main, I've pushed the fix, it should work.
